// flow-typed signature: 16e7434ec2002619632c7cc9acbbab1f
// flow-typed version: <<STUB>>/timezone-mock_v1.2.2/flow_v0.160.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'timezone-mock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'timezone-mock' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'timezone-mock/lib/tzdata' {
  declare module.exports: any;
}

// Filename aliases
declare module 'timezone-mock/index' {
  declare module.exports: $Exports<'timezone-mock'>;
}
declare module 'timezone-mock/index.js' {
  declare module.exports: $Exports<'timezone-mock'>;
}
declare module 'timezone-mock/lib/tzdata.js' {
  declare module.exports: $Exports<'timezone-mock/lib/tzdata'>;
}
