name: Deploy Production

on:
  push:
    branches:
      - master

jobs:
  back-merge:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Merge master -> develop
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          from_branch: master
          target_branch: develop
          github_token: ${{ secrets.GH_TOKEN }}
  deploy: # Runs install once before everything to create & save cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: 14
          cache: 'yarn'
      - run: yarn install
      - name: publish
        run: yarn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
